version: "3.8"

#SERVICES
services:
    # Flask
    flask-python:
        container_name: PythonAPI
        build:
            context: ../server/flask
        # ports:
        #   - "5000:5000"
        volumes:
            - ../server/flask:/app
    # Backend
    # Springboot
    java-springboot:
        container_name: JavaAPI
        build:
            context: ../server/springboot
        depends_on:
            - flask-python
        ports:
            - "8080:8080"
        volumes:
            - ../server/springboot:/app

    nginx-frontend:
        container_name: Frontend
        build:
            context: ../client
        depends_on:
            - java-springboot
        ports:
            - "5173:80"
            - "80:80"
        volumes:
            # - ../client/dist:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
